### ISSUE TITLE
org-pomodoro-third-time-mode is a buffer-local

### ISSUE THREAD

**Issue by meliache** [telotortium/org-pomodoro-third-time#3]
`org-pomodoro-third-time-mode` is a local minor mode. That is, if I enable it and change to a different buffer, the value of the ``org-pomodoro-third-time-mode` variable is `nil`. However, the hooks that the mode sets seem to be global.

I think that for org-pomodoro-third-time it makes more sense to be a global minor mode, e.g. with `define-global-minor-mode`.

Alternatively we can make all hooks buffer-local via the optional argument to `add-hook` and then also add an additional `global-org-pomodoro-third-time-mode` on top of the local mode via `define-globalized-minor-mode`

**Comment by telotortium** [comment]
No, I definitely want this to be a global minor mode. I will fix this soon.

**Comment by meliache** [comment]
Thanks for the quick reaction to my PR's/issues. I find this mode super useful!
