### ISSUE TITLE
1 minute break time on first pomodoro of new day?

### ISSUE THREAD

**Issue by zinbiel576** [telotortium/org-pomodoro-third-time#6]
Hi, great package and great idea, I'm really enjoying working this way. Quick question for you: When I start the first pomodoro of the day (so there's been 12+ hours since the last pomodoro usually), no matter the length of the pomodoro, I always get 1min of break time. So my typical pomodoro length is 55 mins, and right when I start it with `org-pomodor`, I get a message in the minibuffer saying something like

```
actual-break-time 14759.820 delta -14699.820
bank seconds -14699.820
```

I'm guessing that this large number is because it's been so long since the last pomodoro and it's making my first break time 1min despite working for 55mins. Any ideas on why this might be happening? I'd expect the time bank to be zeroed out or something at the end of the work day so it's not dragging down the break time of the first pom the next day. Let me know,thanks!

**Comment by telotortium** [comment]
The `org-pomodoro` should prompt you in this situation to reset pomodoro count. Is it doing so? If you are resetting your Pomodoro count, `org-pomodoro-third-time` *should* detect this. Right now, however, it only does so when finishing the Pomodoro. I can try to add code to detect this at the *start* of the Pomodoro as well.

**Comment by jasoncyu** [comment]
Ah ok I had the expiry time set to a really high number years ago since I don't use the count feature. Setting it to a lower number makes the break time work as expected. Feel free to close, thanks!
