### ISSUE TITLE
[Suggestion] Automatic extension of time

### ISSUE THREAD

**Issue by Ypot** [telotortium/org-pomodoro-third-time#7]
> If you’d like to change your current Pomodoro’s length, either to shorten it because you’re struggling to focus or are interrupted, or to lengthen it because you’re really in the zone, change it with M-x
>     org-pomodoro-third-time-end-in. This prompts you for a number of minutes in the future from now (by default, 10) when the Pomodoro should end. 

Could the Pomodoro be extended automatically? So, we could stay in the zone without worrying about interacting for extending the time.

**Comment by Sabicool** [comment]
I suppose you can set the variable for `org-pomodoro-manual-break` (from the org-pomodoro package) to be true. From the documentation: If non-nil, after the time is up for a pomodoro, an "overtime" state is entered until ‘org-pomodoro’ is invoked, which then finishes the pomodoro and enters the break period.

So I suppose when you want to end the pomodoro session you just run `org-pomodoro-third-time-end-now`. With a little testing, seems to work well for me where the break time incorporates the total length the pomodoro ran for. Perhaps the only thing that might be annoying is the notification to take a break that comes up when the pomodoro is supposed to end.

**Comment by Ypot** [comment]
Correct, thanks. 
I keep testing it, it's nice!
